### ISSUE TITLE
error: [Errno 97] Address family not supported by protocol

### ISSUE THREAD

**Issue by imv7** [arthurnn/SynFlood#1]
```
Exception in thread Thread-24:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "syn.py", line 36, in run
    send(i/t, verbose=0)
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 268, in send
    return __gen_send(conf.L3socket(*args, **kargs), x, inter=inter, loop=loop, count=count,verbose=verbose,
  File "/usr/local/lib/python2.7/dist-packages/scapy/arch/linux.py", line 324, in __init__
    self.ins = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(type))
  File "/usr/lib/python2.7/socket.py", line 191, in __init__
    _sock = _realsocket(family, type, proto)
error: [Errno 97] Address family not supported by protocol
Exception in thread Thread-25:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "syn.py", line 36, in run
    send(i/t, verbose=0)
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 268, in send
    return __gen_send(conf.L3socket(*args, **kargs), x, inter=inter, loop=loop, count=count,verbose=verbose,
  File "/usr/local/lib/python2.7/dist-packages/scapy/arch/linux.py", line 324, in __init__
    self.ins = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(type))
  File "/usr/lib/python2.7/socket.py", line 191, in __init__
    _sock = _realsocket(family, type, proto)
error: [Errno 97] Address family not supported by protocol


Exception in thread Thread-26:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "syn.py", line 36, in run
    send(i/t, verbose=0)
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 268, in send
    return __gen_send(conf.L3socket(*args, **kargs), x, inter=inter, loop=loop, count=count,verbose=verbose,
  File "/usr/local/lib/python2.7/dist-packages/scapy/arch/linux.py", line 324, in __init__
    self.ins = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(type))
  File "/usr/lib/python2.7/socket.py", line 191, in __init__
    _sock = _realsocket(family, type, proto)
error: [Errno 97] Address family not supported by protocol
^CException in thread Thread-27:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "syn.py", line 36, in run
    send(i/t, verbose=0)
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 268, in send
    return __gen_send(conf.L3socket(*args, **kargs), x, inter=inter, loop=loop, count=count,verbose=verbose,
  File "/usr/local/lib/python2.7/dist-packages/scapy/arch/linux.py", line 324, in __init__
    self.ins = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(type))
  File "/usr/lib/python2.7/socket.py", line 191, in __init__
    _sock = _realsocket(family, type, proto)
error: [Errno 97] Address family not supported by protocol


Total packets sent:                     30Traceback (most recent call last):
  File "syn.py", line 39, in <module>
    Exception in thread Thread-28:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "syn.py", line 36, in run
    send(i/t, verbose=0)
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 268, in send
    return __gen_send(conf.L3socket(*args, **kargs), x, inter=inter, loop=loop, count=count,verbose=verbose,
  File "/usr/local/lib/python2.7/dist-packages/scapy/arch/linux.py", line 324, in __init__
    self.ins = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(type))
  File "/usr/lib/python2.7/socket.py", line 191, in __init__
    _sock = _realsocket(family, type, proto)
error: [Errno 97] Address family not supported by protocol
Exception in thread Thread-29:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "syn.py", line 36, in run
    send(i/t, verbose=0)
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 268, in send
    return __gen_send(conf.L3socket(*args, **kargs), x, inter=inter, loop=loop, count=count,verbose=verbose,
  File "/usr/local/lib/python2.7/dist-packages/scapy/arch/linux.py", line 324, in __init__
    self.ins = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(type))
  File "/usr/lib/python2.7/socket.py", line 191, in __init__
    _sock = _realsocket(family, type, proto)
error: [Errno 97] Address family not supported by protocol
sendSYN().start()

  File "/usr/lib/python2.7/threading.py", line 741, in start

Exception in thread Thread-30:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "syn.py", line 36, in run
    send(i/t, verbose=0)
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 268, in send
    return __gen_send(conf.L3socket(*args, **kargs), x, inter=inter, loop=loop, count=count,verbose=verbose,
  File "/usr/local/lib/python2.7/dist-packages/scapy/arch/linux.py", line 324, in __init__
    self.ins = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(type))
  File "/usr/lib/python2.7/socket.py", line 191, in __init__
    _sock = _realsocket(family, type, proto)
error: [Errno 97] Address family not supported by protocol
    Exception in thread Thread-31:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "syn.py", line 36, in run
    send(i/t, verbose=0)
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 268, in send
    return __gen_send(conf.L3socket(*args, **kargs), x, inter=inter, loop=loop, count=count,verbose=verbose,
  File "/usr/local/lib/python2.7/dist-packages/scapy/arch/linux.py", line 324, in __init__
    self.ins = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(type))
  File "/usr/lib/python2.7/socket.py", line 191, in __init__
    _sock = _realsocket(family, type, proto)
error: [Errno 97] Address family not supported by protocol

self.__started.wait()

  File "/usr/lib/python2.7/threading.py", line 614, in wait
    self.__cond.wait(timeout)
  File "/usr/lib/python2.7/threading.py", line 340, in wait
    waiter.acquire()
KeyboardInterrupt
```

**Comment by imv7** [comment]
```

root@DESKTOP-LFS4GJV:/mnt/c/Users/IgorMonteiroVieira/Desktop/xpl# python syn.py 127.0.0.1 3831
^CTraceback (most recent call last):
  File "syn.py", line 10, in <module>
    from scapy.all import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/all.py", line 40, in <module>
```

**Comment by imv7** [comment]
```

root@DESKTOP-LFS4GJV:/mnt/c/Users/IgorMonteiroVieira/Desktop/xpl# scapy
INFO: Can't import matplotlib. Won't be able to plot.
INFO: Can't import PyX. Won't be able to use psdump() or pdfdump().
WARNING: No route found for IPv6 destination :: (no default route?)
INFO: Can't import python Crypto lib. Won't be able to decrypt WEP.
INFO: Can't import python Crypto lib. Disabled certificate manipulation tools
INFO: Can't import python ecdsa lib. Disabled certificate manipulation tools
Welcome to Scapy (2.3.3)
>>>
```
